name: Build PicoShrink

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install cargo-packager
        run: cargo install cargo-packager --locked

      - name: Package
        run: cargo packager --release --formats appimage,deb

      - name: Upload packages
        uses: actions/upload-artifact@v4
        with:
          name: picoshrink-linux
          path: |
            target/release/*.AppImage
            target/release/*.deb

  windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install cargo-packager
        run: cargo install cargo-packager --locked

      - name: Package
        run: cargo packager --release --formats nsis

      - name: Upload packages
        uses: actions/upload-artifact@v4
        with:
          name: picoshrink-windows
          path: target/release/*.exe

  macos:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install cargo-packager
        run: cargo install cargo-packager --locked

      - name: Generate macOS icon
        run: |
          mkdir -p icon.iconset

          cp assets/icon-16.png   icon.iconset/icon_16x16.png
          cp assets/icon-32.png   icon.iconset/icon_16x16@2x.png
          cp assets/icon-32.png   icon.iconset/icon_32x32.png
          cp assets/icon-64.png   icon.iconset/icon_32x32@2x.png
          cp assets/icon-128.png  icon.iconset/icon_128x128.png
          cp assets/icon-256.png  icon.iconset/icon_128x128@2x.png
          cp assets/icon-256.png  icon.iconset/icon_256x256.png
          cp assets/icon-512.png  icon.iconset/icon_256x256@2x.png
          cp assets/icon-512.png  icon.iconset/icon_512x512.png
          cp assets/icon-1024.png icon.iconset/icon_512x512@2x.png

          iconutil -c icns icon.iconset -o assets/icon.icns

      - name: Package
        run: cargo packager --release --formats dmg

      - name: Upload packages
        uses: actions/upload-artifact@v4
        with:
          name: picoshrink-macos
          path: target/release/*.dmg
